### ISSUE TITLE
To be put in the README file. Grub User story

### ISSUE THREAD

**Issue by Hagustin** [Hagustin/GRUB#1]
## READ ME

GRUB APP
##User Story
AS A food lover.
I WANT to be able to view and share my favourite food recipes and pictures.
SO THAT I can expand my culinary knowledge with others with similar interests.

##Acceptance Criteria
GIVEN a username and password I am able to login to the “Grub” app.
WHEN I login I am able to see food categories (Breakfast, Lunch, Dinner, Dessert) that I can view recipes in.
THEN I can create and submit my own recipe to the app, and save these in My Recipes, and save others in Favourite Recipes.
Wireframe and User Flow Diagram attached in the powerpoint file.

**Comment by brankad75** [comment]
All README files need to be consolidated into the GRUB Readme file.
