### ISSUE TITLE
Add Rating and Comments on Recipe Page

### ISSUE THREAD

**Issue by brankad75** [Hagustin/GRUB#8]
# ADD RATING AND COMMENTS ON RECIPE PAGE

## User Story
AS A user who has clicked on a recipe
I WANT to be able to also rate the recipe and provide comment that can be submitted
SO THAT it can be viewed by other FellowGrubs

## Acceptance Criteria
GIVEN a rating and comments section
WHEN I can tick on the number of stars and add a comment
THEN I can click on the submit button to make those available below the recipe for other users to see.

**Comment by Hagustin** [comment]
are the "comments" going to be saved at the local storage?
